#!/usr/bin/env bash
#
# launcher - Launch rerun from an self extracting archive script
#
# generator: @GENERATOR@
# date: @DATE@
# user: @USER@
# archive-version: @VERSION@
# archive-release: @RELEASE@

# Function to print error message and exit
die() { echo "ERROR: $* " >&2 ; exit 1 ; }

# Check for required environment variables 
[ -z "${CWD}" ] && die "CWD not set." ; # user's current working directory
[ -z "${PAYLOAD}" ] && die "PAYLOAD directory not specified." ; # archive artifacts 

# Verify the extracted artifact contents
[ -d ${PAYLOAD}/rerun ] || die "rerun subdirectory not found. CWD=${CWD}, PAYLOAD=$PAYLOAD"
[ -d ${PAYLOAD}/rerun/modules ] || die "missing modules subdirectory"
[ -f ${PAYLOAD}/rerun/rerun ] || die "missing rerun script"
[ -x ${PAYLOAD}/rerun/rerun ] || { chmod +x ./rerun || die "couldn't set rerun executable" ; }

# set the module directory base
export RERUN_MODULES=$PAYLOAD/rerun/modules

export RERUN_LOG_FMT_CONSOLE="[%level%]: %message%"

# add archive rerun script to path
PATH=$PATH:$PAYLOAD/rerun

# Marshalling config properties to command options
# -------------------------------------------------
# Generate a rerun answers file for any of the matching command step options.
# Remove the RD_CONFIG prefix from the variable name.
#
#      RD_CONFIG_MY_PROPNAME --translated--> MY_PROPNAME
#
# Note: assumes RD_* environment variables are passed through.
#env|grep '^RD_'|sort >/tmp/debug.context

ANSWERS=${PAYLOAD}/answers.$$
> "$ANSWERS" ; # truncate 

env | 
while read -r envvar
do 
	varname=${envvar%%=*}
	[[ "${varname:-}" =~ ^RD_CONFIG.+ ]] || continue

	answer_varname=${varname/RD_CONFIG_/}
	answer_value=$(eval echo \$${varname})

	# Skip values if they contain an unresolved context variable.
	[[ "$answer_value" =~ \$\{(option|node|job|config)\..*\} ]] && {
		#echo "DEBUG: value '$VALUE' matches context variable pattern. Skipping it" >> /tmp/debug.context
		continue
	}

	if [[ "${answer_value:-}" = *[[:space:]]* ]]
	then
		printf "%s=\"%s\"\n" "$answer_varname" "$answer_value" >> "$ANSWERS"
	else
		printf "%s=%s\n" "$answer_varname" "$answer_value" >> "$ANSWERS"
	fi
done

#cp $ANSWERS /tmp/debug.answers

# Get ready to run 
declare -a rerun_flags
rerun_flags=( -G ) ; # color enable
rerun_flags+=( "-A $ANSWERS" )

[[ "${RD_JOB_LOGLEVEL}" == "DEBUG" ]] && {
	rerun_flags+=( --loglevel debug )
	rerun_flags+=( -x )
}
[[ -n "${RD_CONFIG_RUN_AS:-}" ]] && {
	rerun_flags+=( -S "$RD_CONFIG_RUN_AS" )
}

#echo >&2 "DEBUG: launcher: rerun_flags: ${rerun_flags[*]:-} $@"

# launch it!
exec "$PAYLOAD/rerun/rerun" ${rerun_flags[@]:-} "$@"

# Done
