# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Wed Jul  8 16:01:47 PDT 2015
#
#/ usage: rundeck-plugin:model-source  --name <>  --version <1.0.0>  --modules <> [ --build-dir <./build>]  --command <>  --format <resourceyaml> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --name) rerun_option_check $# $1; NAME=$2 ; shift ;;
            --version) rerun_option_check $# $1; VERSION=$2 ; shift ;;
            --modules) rerun_option_check $# $1; MODULES=$2 ; shift ;;
            --build-dir) rerun_option_check $# $1; BUILD_DIR=$2 ; shift ;;
            --command) rerun_option_check $# $1; COMMAND=$2 ; shift ;;
            --format) rerun_option_check $# $1; FORMAT=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$VERSION" ] && VERSION="$(rerun_property_get $RERUN_MODULE_DIR/options/version DEFAULT)"
    [ -z "$BUILD_DIR" ] && BUILD_DIR="$(rerun_property_get $RERUN_MODULE_DIR/options/build-dir DEFAULT)"
    [ -z "$FORMAT" ] && FORMAT="$(rerun_property_get $RERUN_MODULE_DIR/options/format DEFAULT)"
    # Check required options are set
    [ -z "$NAME" ] && { echo >&2 "missing required option: --name" ; return 2 ; }
    [ -z "$VERSION" ] && { echo >&2 "missing required option: --version" ; return 2 ; }
    [ -z "$MODULES" ] && { echo >&2 "missing required option: --modules" ; return 2 ; }
    [ -z "$COMMAND" ] && { echo >&2 "missing required option: --command" ; return 2 ; }
    [ -z "$FORMAT" ] && { echo >&2 "missing required option: --format" ; return 2 ; }
    # If option variables are declared exportable, export them.

    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${NAME:=}
: ${VERSION:=}
: ${MODULES:=}
: ${BUILD_DIR:=}
: ${COMMAND:=}
: ${FORMAT:=}


